# Generated by Django 4.1 on 2024-01-24 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banana", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banana",
            name="description",
        ),
        migrations.RemoveField(
            model_name="banana",
            name="image",
        ),
    ]
